### ISSUE TITLE
ci doesn't run on main branch automatically

### ISSUE THREAD

**Issue by djerius** [djerius/pgplot-autotool#5]
Committing to the main branch doesn't run the CI pipeline automatically.

**Comment by zmughal** [comment]
This is because of the `tags-ignore` filter

<https://github.com/djerius/pgplot-autotool/blob/75abca2423aa015a9f3c9f76d4cc345702ee7446/.github/workflows/ci.yml#L4-L5>

In order to run the branch, add:

```yaml
on:
  push:
    branches:
      - 'main'
```
